image: openjdk:11

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .maven/
stages:
  - check
  - build
  - test

before_script:
  - export MAVEN_USER_HOME=`pwd`/.maven

nohttp:
  stage: check
  script:
    - ./mvnw -ntp checkstyle:check -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/checkstyle-*.xml

maven-compile:
  stage: build
  script:
    - ./mvnw -ntp compile -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/classes/
      - target/generated-sources/
    expire_in: 1 day

maven-test:
  stage: test
  script:
    - ./mvnw -ntp verify -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    reports:
      junit: target/surefire-reports/**/TEST-*.xml
    paths:
      - target/surefire-reports
    expire_in: 1 day